#!/bin/sh
docker compose down && \
  docker compose up -d &&
  docker stop iam-apim && \
  docker exec --privileged -u 0 -it iam-is /bin/sh -c 'echo "192.168.25.32 api-dev.novaterr.com" >> /etc/hosts' && \
  docker logs iam-is -f
#api-manager      database         email            identity-server  reverse-proxy
