[server]
hostname = "is-local.dev"
node_ip = "127.0.0.1"
offset = "3"
base_path = "https://$ref{server.hostname}:${carbon.management.port}"

[transport.https.properties]
proxyPort = 443

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[user_store]
type = "database_unique_id"

[database.identity_db]
type = "mysql"
hostname = "iam-db"
name = "WSO2_IDENTITY_DB"
username = "wso2admin"
password = "wso2carbon"
port = "3306"
driver="com.mysql.cj.jdbc.Driver"

[database.shared_db]
type = "mysql"
hostname = "iam-db"
name = "WSO2_SHARED_DB"
username = "wso2admin"
password = "wso2carbon"
port = "3306"
driver="com.mysql.cj.jdbc.Driver"

[output_adapter.email]
from_address = "admin@xetid.cu"
hostname = "iam-email"
port = 25

[keystore.primary]
file_name = "wso2carbon.p12"
password = "wso2carbon"
alias = "wso2is"
key_password = "wso2carbon"
type = "PKCS12"

[trustore]
file_name = "client-trustore.p12"
password = "wso2carbon"
type = "PKCS12"


[account_recovery.endpoint.auth]
hash = "66cd9688a2ae068244ea01e70f0e230f5623b7fa4cdecb65070a09ec06452262"


[identity.auth_framework.endpoint]
app_password = "dashboard"

[role_mgt]
allow_system_prefix_for_role = true

[oauth]
authorize_all_scopes = true


[[resource.access_control]]
context = "(.*)/scim2/Me"
secure = true
http_method = "GET"
cross_tenant = true
permissions = [ ]
scopes = [ ]

# addtional components
[[event_listener]]
id = "token_revocation"
type = "org.wso2.carbon.identity.core.handler.AbstractIdentityHandler"
name = "org.wso2.is.notification.ApimOauthEventInterceptor"
order = 1

[event_listener.properties]
notification_endpoint = "https://iam-apim:9443/internal/data/v1/notify"
username = "${admin.username}"
password = "${admin.password}"
"header.X-WSO2-KEY-MANAGER" = "WSO2-IS"

[[event_handler]]
name = "RegisteringAMLAuditEventHandler"
subscriptions = [ "PRE_ADD_USER" ]


[[event_listener]]
id = "authn-aml-audit-event-handler"
type = "org.wso2.carbon.identity.core.handler.AbstractIdentityHandler"
name = "AuthnAMLAuditEventHandler"
order = 31
enable = true

# health checkers configs
[carbon_health_check]
enable= true

[carbon_health_check.health_checker.data_source_health_checker]
enable = true
order = "90"
pool_usage_limit_percentage = "20"

[carbon_health_check.health_checker.data_source_health_checker.properties]
'monitored.datasources' = "jdbc/WSO2CarbonDB,jdbc/WSO2UM_DB,jdbc/SHARED_DB"

[carbon_health_check.health_checker.server_startup_health_checker]
enable = true
order = "60"

[carbon_health_check.health_checker.super_tenant_health_checker]
enable = true
order = "92"
'monitored.user.stores' = "primary"